# Generated by Django 3.1.1 on 2022-04-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_auto_20220408_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
    ]
