# Generated by Django 3.1.1 on 2022-04-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_remove_property_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
    ]
