# Generated by Django 3.1.1 on 2022-04-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_auto_20220408_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
    ]
