# Generated by Django 3.1.1 on 2022-04-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_remove_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='property',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
