# Generated by Django 3.1.1 on 2022-04-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_auto_20220409_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertytitle', models.CharField(max_length=100, null=True)),
                ('propertydescription', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('bedrooms', models.CharField(max_length=100, null=True)),
                ('bathrooms', models.CharField(max_length=100, null=True)),
                ('floors', models.CharField(max_length=100, null=True)),
                ('garages', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('rentorsaleprice', models.CharField(max_length=100, null=True)),
                ('beforepricelabel', models.CharField(max_length=100, null=True)),
                ('afterpricelabel', models.CharField(max_length=100, null=True)),
                ('propertyid', models.CharField(max_length=100, null=True)),
                ('centercooling', models.CharField(max_length=100, null=True)),
                ('balcony', models.CharField(max_length=100, null=True)),
                ('petfriendly', models.CharField(max_length=100, null=True)),
                ('barbeque', models.CharField(max_length=100, null=True)),
                ('firealarm', models.CharField(max_length=100, null=True)),
                ('modernkitchen', models.CharField(max_length=100, null=True)),
                ('storage', models.CharField(max_length=100, null=True)),
                ('dryer', models.CharField(max_length=100, null=True)),
                ('heating', models.CharField(max_length=100, null=True)),
                ('pool', models.CharField(max_length=100, null=True)),
                ('laundry', models.CharField(max_length=100, null=True)),
                ('sauna', models.CharField(max_length=100, null=True)),
                ('gym', models.CharField(max_length=100, null=True)),
                ('elevator', models.CharField(max_length=100, null=True)),
                ('dishwasher', models.CharField(max_length=100, null=True)),
                ('emergencyexit', models.CharField(max_length=100, null=True)),
                ('featuredimage', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage1', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage2', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage3', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage4', models.FileField(blank=True, null=True, upload_to='')),
                ('galleryimage5', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=300, null=True)),
                ('zipcode', models.CharField(max_length=30, null=True)),
                ('neighborhood', models.CharField(max_length=200, null=True)),
                ('listingdate', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.propertytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.usertype')),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.property'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.property'),
        ),
    ]
