# Generated by Django 3.1.1 on 2022-04-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_auto_20220409_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
