# Generated by Django 3.1.1 on 2022-04-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_delete_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
                ('mobileno', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('enquiryno', models.CharField(max_length=50, null=True)),
                ('enquirydate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('remarkdate', models.DateField(null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.property')),
            ],
        ),
    ]
